### ISSUE TITLE
Translation not working, no errors/log entries

### ISSUE THREAD

**Issue by rschumachr** [dmitryd/dd_deepl#28]
I hope this can be considered an issue, I've consulted the slack channel but couldn't get any solutions there. The page content does not get translated at all, neither do news records. The issue to me is that there is no error/warning/info that would help me find the cause.

I've followed the documentation and double checked everything. Using TYPO3 12.4.11 and latest extension version, included the typoscript in the template, added the typoscript constants and the tsconfig (all are shown as active in the backend with the correct values). The deepl entry shows the correct apiKey and character limit usage. The buttons to translate are all there and can be used but they behave exactly like the standard translate buttons just adding the "[Translate to English:]" in front of titles and not translating anything. Same with news records.

In Slack it was suggested it might have to do with some faulty lines in the config.yaml (site configuration) but I've checked and all appears correct, the way I always set up the languages. Played around with some different values but without success.

It seems to me there should be some warning or error informing me why the content isn't being translated. Would also be helpful if the documentation included how the language settings in the site configuration need to look (which field is used to determine the target language, although I'm assuming it's the locale field).

**Comment by dmitryd** [comment]
Here is my languages are set up:

```yaml
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_CH.UTF-8
    iso-639-1: de
    navigationTitle: De
    hreflang: ''
    direction: ''
    flag: de
    pageTitlePart: 'Snowflake Website Template'
    websiteTitle: ''
  -
    title: English
    enabled: true
    base: /en
    pageTitlePart: ''
    typo3Language: default
    locale: en_US.utf-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
```

What languages do you use?
